language: java
sudo: required
dist: trusty
services:
  - docker
before_install:
  - docker pull yassine/alpine-gobetween
install:
  - mvn package -DskipTests=true
script:
  - mvn test post-integration-test
after_success:
  - mvn coveralls:report